image: geosam/bitbucket-aws-deploy:latest
pipelines:
  tags:
    'v*.*.*':
      - step:
          name: deploy a package
          script:
            - artifact-deploy package --region-name=${AWS_REGION}